### ISSUE TITLE
JRuby 9k warbler config error

### ISSUE THREAD

**Issue by swistaczek** [jruby/warbler#341] opened 2015-09-04 06:49 UTC
## Command
```ruby
bundle exec warble config
```
## Error
```bash
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
warble aborted!
Java::JavaLang::StackOverflowError:
Users.ernest_dot_bursa.$_dot_rbenv.versions.jruby_minus_9_dot_0_dot_0_dot_0.lib.ruby.stdlib.tsort_dot_rb.RUBY$block$each_strongly_connected_component$3(/Users/ernest.bursa/.rbenv/versions/jruby-9.0.0.0/lib/ruby/stdlib/tsort.rb:347)
org.jruby.runtime.CompiledIRBlockBody.commonYieldPath(CompiledIRBlockBody.java:70)
org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:139)
org.jruby.runtime.BlockBody.yield(BlockBody.java:77)
```
Full stack: https://gist.github.com/swistaczek/1e8f037822b753b2a1f1

**Comment by jkutner** [comment] 2015-09-09 19:45
I wasn't able to reproduce this. Can you provide a little more detail about your environment? What OS, what version of Warbler?

**Comment by kares** [comment] 2015-09-10 05:54
... and maybe try **9.0.1.0** now that it's releases - seems like a JRuby bug ... so far

**Comment by tidelake** [comment] 2015-09-10 13:06
Using warbler 2.0.0.rc1 and jruby-9.0.0.0 on Mac 10.10.5
```
[phoenix (master)]$ bundle exec warble config
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC, please help us finish 4.2 support - check http://bit.ly/jruby-42 for starters
cp /Users/jess1/.rvm/gems/jruby-9.0.0.0/gems/warbler-2.0.0.rc1/warble.rb config/warble.rb
```
Created `config/warble.rb` but threw that error.

**Comment by kares** [comment] 2015-09-10 13:20
0. first of all please try 9.0.1.0 as advised
1. than mind the **NOTE: ActiveRecord 4.2 is not (yet) fully supported by AR-JDBC** as it might be dua an unsupported adapter please confirm if this happens with 4.1 as well

**Comment by egomolka** [comment] 2015-09-26 21:59
Hi:
I am also interested in this resolution for this bug. I get the "close_others" warning when running the command "jruby -S bundle exec warble":

"uri:classloader:/jruby/kernel/kernel.rb:17: warning: unsupported exec option: close_others"

I am testing under JRuby 9.0.1.0, I get the same warning under both activerecord 4.2.4 and activerecord 4.0.13.

**Comment by jkutner** [comment] 2015-10-31 20:29
Closing at not a bug since this is a Bundler thing. let me know if you have other issues.

**Closed by jkutner** 2015-10-31 20:29 UTC
